---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Provision VM from Template
    name: template
    inherits: 
    description: 
  fields:
  - AcquireIPAddress:
      value: "/Integration/MIQ_IPAM/IPAM_Methods/miq_acquire_ip_address"
  - Provision:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/Provision"
  - CheckProvisioned:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned"
  - RegisterDHCP:
      value: "/Integration/Methods/add_to_service"
  - ActivateCMDB:
      value: "/Integration/Methods/order_ansible_playbook"
