---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: order_ansible_playbook
    inherits: 
    description: 
  fields:
  - method1:
      value: order_ansible_playbook
